from eclair.agent.execute.validators.field_focused_before_type import FieldFocusedBeforeTypeValidator
from eclair.agent.execute.validators.field_value_after_type import FieldValueAfterTypeValidator
from eclair.agent.execute.validators.page_is_loaded import PageIsLoadedValidator
from eclair.agent.execute.validators.scroll_changed_screen import ScrollChangedScreenValidator
from eclair.agent.execute.validators.action_sugg_is_diff_than_prev import ActionSuggestionIsDiffThanPrevActionValidator
from eclair.agent.execute.validators.field_empty_before_type import FieldEmptyBeforeTypeValidator
from eclair.agent.execute.validators.click_coords_within_element import ClickCoordinatesWithinElementValidator